backend:
  name: github
  repo: testFactoryGreat/boilerplate-site-fabrica
  branch: master
  site_domain: test-factory-great.netlify.app

publish_mode: editorial_workflow
media_folder: "static/assets/img" 
public_folder: "assets/img"

collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Resume", name: "resume", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
